<!-- Page d'ajout d'un article -->
<h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="add_article.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" rows="15">
            </li>
            <li>

                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>

                <select id="author" name="author">
                    <?php foreach($authors as $author): ?>
                    <option value="<?= $author['id'] ?>">
                        <?= $author['firstName']." ".$author['lastName'] ?>
                    </option>
                    <?php endforeach ?>
                </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach($categories as $category): ?>
                    <option value="<?= $category['id'] ?>">
                        <?= $category['titles']?>
                    </option>
                    <?php endforeach ?>
                </select>
            </li>
                <input type="file" name="fichier" accept="image/gif" />
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>

  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
