
<!-- Blog -->
<div class="container">
    <div class="row">
        <h1>Publications</h1>
    </div>
</div>

<img class="img-responsive" alt="Palais de justice" src="img/code-civil.png">

<div class="container">
    <div class="row centered">
        <ul class="post-list">
            <?php foreach($articles as $article): ?>
                <li class="post">
                    <h2>
                        <a href="show_post.php?id=<?= $article['id'] ?>" title="Consulter l'article">
                            <i class="fa fa-pencil-square-o"></i>
                            <?= $article['title'] ?>
                        </a>
                    </h2>
                    <article>
                        <?= strip_tags(substr($article['content'], 0, 600)) ?> [...] <a href="show_post.php?id=<?= $article['id'] ?>" class="link-blog" title="Consulter l'article"> Lire la suite ></a>
                        <p></p>
                        
                    </article>
                    <small>
                        Rédigé par <?= $article['firstName']." ".$article['lastName'] ?> le <?= $article['creationTimestamp'] ?>
                    </small>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>