<!-- Domaines d'intervention -->
<div class="container">
  <div class="row">
    <h1>Domaines d'intervention</h1>
  </div>
</div>

<img class="img-responsive" alt="Palais de justice" src="img/domaines-intervention-avocat.png">

<!-- Contenu -->
<div class="container">
  <div class="row">
    <!-- Droit 1 -->
    <h2 id="droit-affaires" class="titre-important"><i class="intervention fa fa-bank"></i> Droit des affaires & Droit économique (CONTENU A CHANGER)</h2>
      <h3>Droit commercial</h3>
        <p>Le droit commercial est une partie du droit privé et spécifiquement du droit des affaires, régissant l'exercice de la profession de commerçant et définissant le régime juridique applicable aux actes de commerce.</p>
      <h3>Droit des contrats</h3>
        <p>Le droit des contrats est la branche du droit civil français qui étudie les contrats. Le droit des contrats est lui-même une branche du droit des obligations, tout comme le droit de la responsabilité. Le droit des contrats a été codifié dès 1804 selon la théorie des Lumières sous l'emprise philosophique de l'autonomie de la volonté. Dès lors, le droit des contrats en France est soumis à trois grands principes fondamentaux : la liberté contractuelle, le consensualisme et la force obligatoire du contrat. La théorie de l'autonomie de la volonté doit tout de même être relativisée puisqu'elle est active dans les limites de la loi.</p>
      <h3>Droit de la distribution</h3>
        <p>Le droit de la distribution est constitué du cadre juridique encadrant les relations commerciales entres les industriels / fournisseurs et les enseignes de distribution.<br>
        L’objectif du droit de la distribution est de concilier les impératifs de la liberté du commerce avec des objectifs de protection de l’état de concurrence et de protection des PME face aux abus éventuels de la grande distribution. Le droit de la distribution encadre donc les relations fournisseurs / grande distribution, mais également les formes de distribution particulières (Franchise, distribution sélective, etc.).</p>
      <h3>Droit de la communication</h3>
        <p>Le droit de la communication est une spécialité ayant trait à l'étude des médias, leurs structures, leurs organisations, leurs composantes. Le droit de la communication s'intéresse au statut des journalistes, des agences de presse, des messageries de presse, ainsi qu'au principe de libre circulation des idées et des opinions (avec ses limites).<br>
        Tout le droit de la communication repose sur l'article 11 de la Déclaration des droits de l'homme et du citoyen de 1789 : « La libre communication des pensées et des opinions est un des droits les plus précieux de l'Homme : tout Citoyen peut donc parler, écrire, imprimer librement, sauf à répondre de l'abus de cette liberté dans les cas déterminés par la Loi. »</p>
      <h3>Droit de la consommation</h3>
        <p>Droit qui définit et régit les relations entre les consommateurs et les professionnels. Le droit de la consommation fait partie du droit privé.</p>
      
      <!-- Droit 2 -->
      <h2 id="droit-propriete" class="titre-important"><i class="intervention fa fa-book"></i> Droit de la propriété intellectuelle</h2>
        <p>Le terme “propriété intellectuelle” désigne les œuvres de l’esprit : inventions; œuvres littéraires et artistiques; dessins et modèles; et emblèmes, noms et images utilisés dans le commerce.</p>
        <p>La propriété intellectuelle est protégée par la loi, par exemple au moyen de brevets, de droits d’auteur et d’enregistrements de marques, qui permettent aux créateurs de tirer une reconnaissance ou un avantage financier de leurs inventions ou créations. En conciliant de manière appropriée les intérêts des innovateurs et ceux du grand public, le système de la propriété intellectuelle vise à favoriser un environnement propice à l’épanouissement de la créativité et de l’innovation.</p>

      <!-- Droit 3 -->
      <h2 id="droit-presse" class="titre-important"><i class="intervention fa fa-newspaper-o"></i> Droit de la presse</h2>
        <h3>Droit des contrats</h3>
          <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <h3>Droit de la distribution</h3>
          <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      
      <!-- Droit 4 -->
      <h2 id="droit-construction" class="titre-important"><i class="intervention fa fa-wrench"></i> Droit de la construction</h2>
        <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      
      <!-- Droit 5 -->
      <h2 id="droit-travail" class="titre-important"><i class="intervention fa fa-black-tie"></i> Droit du travail</h2>
        <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      
      <!-- Droit 2 -->
      <h2 id="droit-corporel" class="titre-important"><i class="intervention fa fa-wheelchair"></i> Droit de la réparation du dommage corporel</h2>
        <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>