<!-- Honoraires -->
<div class="container">
      <div class="row">
            <h1>Honoraires</h1>
      </div>
</div>

<img class="img-responsive" alt="Faculté de droit" src="img/cours-de-cassation.png">

<!-- Contenu -->
<div class="container">
	<div class="row">
		<h2>En attente de contenu</h2>
		<p>Après une maîtrise effectuée à Stockholm, en Suède, elle a obtenu un DESS de Droits immatériels de l’entreprise et nouvelles technologies de l’Université Aix-Marseille III puis un DEA de Droit des affaires de l’Université Paris II Panthéon-Assas.</p>
	</div>
</div>