<!-- Page d'accueil -->

<img class="img-responsive" alt="Palais de justice" src="img/Palais_de_Justice.png">

<div class="container">
  <div class="row">
      <h1>Maître Caroline BECARD-MARINETTI</h1>
  </div>
</div>

<!-- Contenu -->
<div class="container">
  <div class="row">
    <div class="container text-justify">
      <ul class="col-md-12 nav nav-pills">
        <li class="col-md-2"><a href="domaines-intervention.php?#droit-affaires"><i class="fa fa-bank"></i> Droit des affaires & Droit économique</a></li>
        <li class="col-md-2"><a href="domaines-intervention.php?#droit-propriete"><i class="fa fa-pencil"></i> Droit de la propriété intellectuelle</a></li>
        <li class="col-md-2"><a href="domaines-intervention.php?#droit-presse"><i class="fa fa-newspaper-o"></i> Droit de la presse</a></li>
        <li class="col-md-2"><a href="domaines-intervention.php?#droit-construction"><i class="fa fa-wrench"></i> Droit de la construction</a></li>
        <li class="col-md-2"><a href="domaines-intervention.php?#droit-travail"><i class="fa fa-black-tie"></i> Droit du travail</a></li>
        <li class="col-md-2"><a href="domaines-intervention.php?#droit-corporel"><i class="fa fa-wheelchair"></i> Droit de la réparation du dommage corporel</a></li>
      </ul>
      <p class="content-standard">Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p class="content-standard">Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea  aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
      <p class="content-standard">Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>


    </div>
  </div>
</div>






