<div class="container">
    <div class="row">
        <h1>Connexion</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form class="generic-form" action="login.php" method="post">
            <fieldset>
                
                    <ul>
                   <!-- Username -->
                    <div class="form-group">
                        <li>
                            <label for="username">Identifiant </label>
                            <input class="form-control" type="text" id="username" name="username" required>
                        </li> 
                    </div>
                    <!-- Password -->
                    <div class="form-group">
                        <li>
                            <label for="password">Mot de passe </label>
                            <input class="form-control" type="password" id="password" name="password" required>  
                        </li>
                    </div>
                    <div class="form-group">
                        <li>
                            <button class="btn btn-primary" type="submit">Se connecter</button>
                            <a class="btn btn-cancel" href="index.php">Annuler</a>
                        </li>
                    </div>
                    </ul>
                </div>
            </fieldset>
        </form>
    </div>
</div>