<!-- Présentation -->

<div class="container">
      <div class="row">
            <h1>Maître Caroline BECARD-MARINETTI est avocat au Barreau de Paris depuis mai 2005.</h1>
      </div>
</div>

<img class="img-responsive" alt="Faculté de droit" src="img/droit.png">

<!-- Contenu -->
<div class="container">
	<div class="row">
		<h2>Formation</h2>
		<p>Après une maîtrise effectuée à Stockholm, en Suède, elle a obtenu un DESS de Droits immatériels de l’entreprise et nouvelles technologies de <a href="http://www.univ-amu.fr/">l’Université Aix-Marseille III</a> puis un DEA de Droit des affaires de <a href="https://www.u-paris2.fr/fr"> l’Université Paris II Panthéon-Assas</a>.</p>

		<h2>Expérience</h2>
		<p>Elle a ensuite exercé au sein du cabinet <a href="http://www.hadengue-associes.com/Caroline-BECARD-MARINETTI.cfm">HADENGUE & Associés</a>, en contentieux de droit des affaires et en droit de la consommation notamment pour des entreprises relevant du secteur des télécommunications.</p>
		<p>Elle y a acquis une solide expérience en droit de la propriété intellectuelle (droit des marques, droit d’auteur, droit des dessins et modèles) et en droit des affaires, notamment en droit de la distribution, droit de la communication, droit commercial et en droit de la construction.</p>
		
		<!-- Sépérateur -->
		<div class="title-middle">AUJOURD’HUI</div>
		
		<h2>Contentieux</h2>
		<p>Maître Caroline BECARD-MARINETTI intervient auprès d’entreprises confrontées à des litiges d’ordre commercial : </p>

			<ul class="container list-bullpoint">
				<li>Responsabilité contractuelle,</li>
				<li>Responsabilité contractuelle,</li>
				<li>Droit de la franchise,</li>
				<li>Rupture brutale de relations commerciales établies,</li>
				<li>Bail commercial,</li>
				<li>Recouvrement de créances,</li>
			</ul>
		<p>et relevant du droit de la propriété intellectuelle :</p>
			<ul class="container list-bullpoint">	
				<li>Contrefaçon,</li>
				<li>Concurrence déloyale.</li>
			</ul>
		<h2>Conseil</h2>
		<p>Elle conseille également les entreprises en matière de rédaction de contrats de nature commerciale et de protection des droits de la propriété intellectuelle :</p>
			<ul class="container list-bullpoint">
				<li>Dépôts INPI,</li>
				<li>Cession de droits.</li>
			</ul>
		<h2>Clientèle de particulier</h2>
		<p>Elle a par ailleurs développée une expérience en contentieux de droit du travail et en réparation du dommage corporel. Elle intervient donc également auprès de particuliers dans ces domaines ainsi qu’en matière de droit des assurances et de droit de la presse :</p>
			<ul class="container list-bullpoint">
				<li>Diffamation et injure ,</li>
				<li>e-réputation,</li>
				<li>Protection de la vie privée.</li>
			</ul>

	</div>
</div>