<form class="generic-form" action="register.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> S'inscrire</legend>
        <ul>
            <li>
                <label for="username">Votre identifiant </label>
                <input type="text" id="username" name="username" required>
            </li>
            <li>
                <label for="password">Votre mot de passe </label>
                <input type="password" id="password" name="password" required>
            </li>
            <li>
                <label for="password">Confirmer votre de passe </label>
                <input type="password" id="confirm_password" name="confirm_password" required>
            </li>
            <li>
                <button class="button button-primary" type="submit">Valider</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>