<!-- Page d'ajout d'un article -->
<div class="container">
    <div class="row">
        <h1>Page non trouvée</h1>
        <h2>Le cabinet vous renseigne sur demande</h2>
        <p>Vous pouvez nous contacter en remplissant le formulaire dans la page Contact ou en cliquant sur ce bouton : </p>
        <a href="contact.php" class="btn btn-primary">Nous contacter</a>
    </div>
</div>

<img class="img-responsive" alt="Palais de justice" src="img/Palais_de_Justice.png">
