<!-- Page d'ajout d'un article -->
<div class="container">
    <div class="row">
        <h1><i class="fa fa-pencil"></i> Rédiger un nouvel article</h1>
    </div>
</div>

<!-- Formulaire de saisie d'un nouvel article -->
<div class="container">
    <div class="row col-lg-12">
        <form class="generic-form" action="add_article.php" method="post" enctype="multipart/form-data">
            <fieldset>
                <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
                <ul class="list-bullpoint list-bullpoint-blog">
                    <li>
                        <div class="form-group">
                            <label for="title">Titre :</label>
                            <input type="text" id="title" name="title" class="form-control">
                        </div>
                    </li>
                    <li>
                        <label class="textarea" for="contents">Article :</label>
                        <textarea id="contents" name="contents" rows="10"></textarea>
                    </li>
                    <br>
                    <br>
                    <li>
                        <label for="author">Auteur :</label>
                        <select id="author" name="author">
                            <?php foreach($authors as $author): ?>
                                <option value="<?= $author['id'] ?>">
                                    <?= $author['firstName']." ".$author['lastName'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </li>
                    <br>
                    <li>
                        <label for="category">Catégorie :</label>
                        <select id="category" name="category">
                            <?php foreach($categories as $category): ?>
                                <option value="<?= $category['id'] ?>">
                                    <?= $category['titles']?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </li>
                    <br>
                    <li>
                        <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Publier</button>
                        <a class="btn btn-danger" href="admin.php"><i class="fa fa-times"></i> Annuler</a>
                    </li>
                </ul>
            </fieldset>
        </form>

        <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
        <script>tinymce.init({ selector:'textarea' });</script>
    </div>
</div>