<!-- Contact -->

<?php if($flashBag->hasMessages()):	?>
    <p class="notice"><?=	$flashBag->fetchMessage() ?></p>
    <hr>
<?php endif; ?>

<div class="container">
    <div class="row">
        <h1>Contact</h1>
    </div>
</div>

<img class="img-responsive" alt="Palais de justice" src="img/contact.png">

<!-- Contenu -->
<div class="container">
    <div class="row col-lg-12">
        <h2>Pour contacter le cabinet</h2>
        <p>Vous pouvez contacter le cabinet pour une prise de rendez-vous ou pour un renseignement d'ordre tarifaire, par téléphone, par email ou à l'aide du formulaire ci-dessous.</p>
    </div>
</div>
<div class="container">
    <div class="row">
        <!-- Coordonnées et MAP -->
        <div class="no-padding-left col-lg-5">
            <address>
                <h4 class="comment-form-legend">Adresse</h4>
                <p class="contact-p">62 rue de Maubeuge - 75009 PARIS</p>
                <h4 class="comment-form-legend">Coordonnées</h4>
                <ul class="list-bullpoint list-bullpoint-blog">
                    <li><abbr title="Téléphone">Tel :</abbr><a href="tel:+33185086887"> +33 1 85 08 68 87</a></li>
                    <li><abbr title="Fax">Fax :</abbr> +33 1 42 81 36 43</li>
                    <li><abbr title="e-mail">E-mail</abbr> : <a href="mailto:cmarinetti@hotmail.fr">cmarinetti@hotmail.fr</a></li>
                </ul>
                <div class="row"><p></p></div>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2623.911161896094!2d2.3453148156751076!3d48.87897007928955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e6a61093591%3A0x244daa8b619c7c75!2s62+Rue+de+Maubeuge%2C+75009+Paris!5e0!3m2!1sfr!2sfr!4v1479748573891" width="" height="" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </address>
        </div>

        <!-- Formulaire de contact -->
        <!-- TODO : - mettre en required les champs 
                    - Rajouter des champs pour affiner la recherche : profession, type de demande...
        -->
        <div class="col-lg-7">

            <h4 class="comment-form-legend">Pour me contacter, remplissez le formulaire suivant : </h4>

            <form action="send_form.php" method="post" onsubmit="return valider()" name="formSaisie">
                <div class="row">
                    <!-- Prénom -->
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <input type="text" class="form-control" name="firstname" id="firstName" placeholder="Votre prénom" required>
                        </div>
                    </div>

                    <!-- Nom -->
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <input type="text" class="form-control" name="lastname" id="lastName" placeholder="Votre nom" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- Email -->
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Votre email" required>
                        </div>
                    </div>
                    <!-- Téléphone -->
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <input type="tel" class="form-control" name="phone" id="phone" placeholder="Votre téléphone" maxlength="13" required>
                        </div>
                    </div>
                </div>
                <!-- Message -->
                <div class="form-group">
                    <textarea class="form-control" id="message" name="message" placeholder="Votre message" rows="10" required></textarea>
                </div>
                <!-- Bouton d'envoi -->
                <button type="submit" value="OK" class="btn btn-primary"><i class="fa fa-check"></i> Envoyer</button>
            </form>

        </div>

    </div>
</div>
