<!-- Domaines d'intervention -->
<div class="container">
  <div class="row">
    <h1>Domaines d'intervention</h1>
  </div>
</div>

<img class="img-responsive" alt="Palais de justice" src="img/domaines-intervention-avocat.png">

<!-- Contenu -->
<div class="container">
  <div class="row col-lg-12">
    <!-- Droit 1 -->
    <h2 id="droit-affaires"><i class="intervention fa fa-briefcase"></i> Droit des affaires & Droit économique :</h2>
      <ul class="list-bullpoint">
          <li>Droit commercial</li>
          <li>Droit de la distribution</li>
          <li>Droit des contrats</li>
          <li>Droit de la consommation</li>
          <li>Droit de la communication</li>
      </ul>

      <!-- Droit 2 -->
      <h2 id="droit-propriete"><i class="intervention fa fa-paint-brush"></i> Droit de la propriété intellectuelle :</h2>
      <ul class="list-bullpoint">
          <li>Droit des marques</li>
          <li>Droit d'auteur</li>
          <li>Droit des dessins et modèles</li>
      </ul>

      <!-- Droit 3 -->
      <h2 id="droit-presse"><i class="intervention fa fa-newspaper-o"></i> Droit de la presse :</h2>
      <ul class="list-bullpoint">
          <li>Droit à l'image et protection de la vie privée</li>
          <li>e-réputation</h3></li>
      </ul>

      <!-- Droit 4 -->
      <h2 id="droit-construction" class="titre-important"><i class="intervention fa fa-wrench"></i> Construction / droit immobilier :</h2>
      <ul class="list-bullpoint">
          <li>Responsabilité décennale</li>
          <li>Baux d'habitation, litiges de copropriété</li>
      </ul>
      <!-- Droit 5 -->
      <h2 id="droit-travail"><i class="intervention fa fa-black-tie"></i> Droit du travail (conflits individuels du travail)</h2>
      <!-- Droit 2 -->
      <h2 id="droit-corporel"><i class="intervention fa fa-wheelchair"></i> Réparation du dommage corporel</h2>
  </div>
</div>
