<!-- Honoraires -->
<div class="container">
      <div class="row">
            <h1>Honoraires</h1>
      </div>
</div>

<img class="img-responsive" alt="Faculté de droit" src="img/cours-de-cassation.png">

<!-- Contenu -->
<div class="container">
	<div class="row col-lg-12">
		<h2>Le cabinet vous renseigne sur demande</h2>
        <p>Les honoraires du Cabinet sont établis en fonction de la nature, de la complexité et de l'urgence de l'affaire.</p>
        <p>Le Cabinet se tient à votre disposition pour toute demande tarifaire.</p>
        <a href="contact.php" class="btn btn-primary">Nous contacter</a>
	</div>
</div>