<!-- Page d'accueil -->

<img class="img-responsive" alt="Palais de justice" src="img/Palais_de_Justice.png">

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>Maître Caroline BECARD-MARINETTI</h1>
        </div>
    </div>
</div>

<!-- Contenu -->
<div class="nav-hp-container container">
    <ul class="nav-hp-ul col-lg-12 nav nav-pills">
        <li class="nav-hp-li col-lg-2"><a class="nav-hp-a" href="domaines-intervention.php?#droit-affaires"><i class="fa fa-briefcase"></i> Droit des affaires & Droit économique</a></li>
        <li class="nav-hp-li col-lg-2"><a class="nav-hp-a" href="domaines-intervention.php?#droit-propriete"><i class="fa fa-paint-brush"></i> Droit de la propriété intellectuelle</a></li>
        <li class="nav-hp-li col-lg-2"><a class="nav-hp-a" href="domaines-intervention.php?#droit-presse"><i class="fa fa-newspaper-o"></i> Droit de la presse</a></li>
        <li class="nav-hp-li col-lg-2"><a class="nav-hp-a" href="domaines-intervention.php?#droit-construction"><i class="fa fa-wrench"></i> Droit de la construction</a></li>
        <li class="nav-hp-li col-lg-2"><a class="nav-hp-a" href="domaines-intervention.php?#droit-travail"><i class="fa fa-black-tie"></i> Droit du travail</a></li>
        <li class="nav-hp-li col-lg-2"><a class="nav-hp-a" href="domaines-intervention.php?#droit-corporel"><i class="fa fa-wheelchair"></i> Droit de la réparation du dommage corporel</a></li>
    </ul>
</div>






