<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Caroline BECARD-MARINETTI - Avocat <?php if(isset($title)):?> - <?= $title; endif ?></title>
    <meta name="description" content="Maître Caroline BECARD-MARINETTI est avocat au Barreau de Paris depuis 2005. ELle est spécialisée en contentieux et conseille également les entreprises en matière de rédaction de contrats. " />

    <!-- Feuilles de style externes -->
    <link rel="stylcxesheet" href="css/normalize-3.0.3.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Cormorant+Garamond|Pontano+Sans" rel="stylesheet">

    <link rel="icon" type="image/png" href="favicon.ico" />

    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
    <meta name = "format-detection" content = "telephone=no" />
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
    <meta name="author" content="Your name">
    <link rel="stylesheet" href="css/bootstrap.css" >
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/camera.css">

    <script src="js/jquery.js"></script>
    <script src="js/jquery-migrate-1.2.1.js"></script>
    <script src="js/superfish.js"></script>
    <script src="js/jquery.mobilemenu.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.ui.totop.js"></script>
    <script src="js/jquery.touchSwipe.min.js"></script>
    <script src="js/jquery.equalheights.js"></script>


    <script src='js/camera.js'></script>
    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="js/jquery.mobile.customized.min.js"></script>
    <!--<![endif]-->

    <script>
        $(window).load( function(){

            jQuery('.camera_wrap').camera();

        });
    </script>
</head>
<body>

<!--==============================header=================================-->
<header id="header">
    <div class="container logo-block">
        <div class="navbar-brand navbar-brand_">
            <a class="logo-CBM-a" href="index.php">
                <h1 class="logo-CBM-h1">CBM
                    <span class="logo-CBM-avocat">Avocat</span>
                    <i class="fa fa-bank"></i>
                </h1>
            </a>
        </div>
    </div>
    <div class="nav-header-menuheader menuheader">
        <div class="nav-header-container container">
            <nav class="nav-header-tm_navbar tm_navbar" role="navigation">
                <ul class="nav-header-ul nav sf-menu">
                    <li class="nav-header-li" ><a class="nav-header-a" href="presentation.php">Présentation</a></li>
                    <li class="nav-header-li" ><a class="nav-header-a" href="domaines-intervention.php">Domaines d'intervention</a></li>
                    <li class="nav-header-li" ><a class="nav-header-a" href="honoraires.php">Honoraires</a></li>
                    <li class="nav-header-li" ><a class="nav-header-a" href="blog.php">Publications</a></li>
                    <li class="nav-header-li" ><a class="nav-header-a" href="contact.php">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<!--==============================content=================================-->

<!-- MAIN -->

<!-- Chargement du template PHTML -->
<?php include $template.'.phtml' ?>


<!--==============================footer=================================-->
<footer>
    <div class="footer-container-fluid container-fluid">
        <div class="footer-row row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <nav>
                    <ul class="footer-ul nav navbar-bottom">
                        <li class="footer-li"><a class="footer-a" href="presentation.php">Présentation</a></li>
                        <li class="footer-li"><a class="footer-a" href="domaines-intervention.php">Domaines d'intervention</a></li>
                        <li class="footer-li"><a class="footer-a" href="honoraires.php">Honoraires</a></li>
                        <li class="footer-li"><a class="footer-a" href="blog.php">Publications</a></li>
                        <li class="footer-li"><a class="footer-a" href="contact.php">Contact</a></li>
                        <li class="footer-li"><a class="footer-a" href="mentions-legales.php">Mentions légales</a></li>
                        <?php if (!isset($_SESSION['auth'])) : ?>
                            <li class="footer-li"><a class="footer-a" href="login.php">Connexion</a>
                        <?php else : ?>
                            <li class="footer-li"><a class="footer-a" href="admin.php">Administration</a></li>
                            <li class="footer-li"><a class="footer-a" href="logout.php">Deconnexion</a></li>
                        <?php endif ?>
                    </ul>
                </nav>
                <div class="footer-text">
                        <p>Maître Caroline BECARD-MARINETTI - Le cabinet : 62 rue de Maubeuge, 75009 PARIS</p>
                        <p>
                            <abbr title="e-mail">E-mail</abbr> : <a href="mailto:cmarinetti@hotmail.fr">cmarinetti@hotmail.fr</a> -
                            <abbr title="Téléphone">Tél</abbr> : <a href="tel:+33185086887">+33 1 85 08 68 87</a> -
                            <abbr title="Fax">Fax</abbr> : +33 1 42 81 36 43</p>
                </div>
                <div class="footer-text">
                    <p>
                        <em id="trade-mark">©CBM 2017<em>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="js/bootstrap.min.js"></script>
<script src="js/tm-scripts.js"></script>
<script src="js/main.js"></script>
</body>
</html>