<div class="container">
    <div class="row">
        <h1>Connexion</h1>
    </div>
</div>
<div class="container">
    <div class="row col-lg-12">
        <form class="generic-form" action="login.php" method="post">
            <fieldset>
                <ul class="list-bullpoint-blog">
                    <div class="row">
                        <!-- Username -->
                        <li class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                            <div class="form-group">

                                <label class="comment-form-label" for="username">Identifiant </label>
                                <input class="form-control" type="text" id="username" name="username" required>
                            </div>
                        </li>

                    </div>
                    <!-- Password -->
                    <div class="row">
                        <li class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="comment-form-label list-bullpoint-blog" for="password">Mot de passe </label>
                                <input class="form-control" type="password" id="password" name="password" required>
                            </div>
                        </li>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <li>
                                <button class="btn btn-primary" type="submit">Se connecter</button>
                                <a class="btn btn-danger" href="index.php">Annuler</a>
                            </li>

                        </div>
                    </div>
                </ul>
            </fieldset>
        </form>
    </div>
</div>