<!-- Présentation -->

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1>Maître Caroline BECARD-MARINETTI est avocat au Barreau de Paris depuis 2005</h1>
        </div>
    </div>
</div>

<img class="img-responsive" alt="Faculté de droit" src="img/droit.png">

<!-- Contenu -->
<div class="container">
    <div class="row col-lg-12">
        <div id="photo-caroline" class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
            <img  src="img/maitre-caroline-becart-marinetti.png">
        </div>


        <h2>Formation</h2>
        <p>Après une maîtrise effectuée à Stockholm, en Suède, Maître Caroline BECARD-MARINETTI a obtenu un DESS de Droits immatériels de l’entreprise et nouvelles technologies de <a href="http://www.univ-amu.fr/">l’Université Aix-Marseille III</a> puis un DEA de Droit des affaires de <a href="https://www.u-paris2.fr/fr"> l’Université Paris II Panthéon-Assas</a>.</p>

        <h2>Expérience</h2>
        <p>Elle a ensuite exercé pendant six ans au sein du cabinet P. CUSSAC. Elle y a acquis une solide expérience en droit de la propriété intellectuelle (droit des marques, droit d'auteur, droit des dessins et modèles) ainsi qu'en droit des affaires et plus spécifiquement en droit de la distribution, droit commercial, droit de la communication et droit de la construction, pour des entreprises relevant du secteur de la grande distribution, de la publicité et du génie thermique.</p>
        <p>Elle a ensuite exercé pendant près de quatre ans, au sein du cabinet <a href="http://www.hadengue-associes.com/Caroline-BECARD-MARINETTI.cfm">HADENGUE & Associés</a>, principalement en contentieux de droit des affaires et en droit de la consommation, notamment pour des entreprises relevant du secteur des télécommunications.</p>


        <!-- Sépérateur -->
        <div>
            <h3 class="separateur">AUJOURD’HUI</h3>
        </div>


        <h2>Contentieux</h2>
        <p>Maître BECARD-MARINETTI accompagne et représente les entreprises et particuliers confrontés à des :</p>
        <ul class="list-bullpoint">
            <li>Litiges de nature commerciale ayant notamment pour objet :</li>
            <ul class="list-bullpoint">
                <li>L'exécution de contrat d'approvisionnement ou de franchise,</li>
                <li>La rupture brutale de relation commerciale établie,</li>
                <li>L'exécution de bail commercial,</li>
                <li>Le recouvrement de créances.</li>
            </ul>
            <li>Litiges relevant de la propriété intellectuelle, en particulier la contrefaçon de marques, de droit d'auteur et de dessins et modèles. </li>
        </ul>
        <p>Elle intervient aussi en contentieux de droit du travail, en droit de la presse (diffamation, injure, protection de la vie privée, droit à l'image), ainsi qu'en réparation du dommage corporel et en droit des assurances.</p>

        <h2>Conseil</h2>
        <p>Maître Caroline BECARD-MARINETTI conseille également les entreprises en matière de :</p>
        <ul class="list-bullpoint">
            <li>Rédaction de contrats,</li>
            <li>Protection des droits de propriété intellectuelle (dépôts auprès de l'INPI, cession de droits de propriété intellectuelle).</li>
        </ul>
        </ul>
    </div>
</div>