
<!-- Article du blog -->
<div class="container">
    <div class="row col-lg-12">
        <section>
            <h2 class="text-center"><sup><i class="fa-blog-post fa fa-quote-left"></i></sup> <?= $article['articleTitle'] ?> <sub><i class="fa-blog-post fa fa-quote-right"></i></sub></h2>
            <hr>
            <article class="show-post-article">
                <?=  wordwrap(nl2br($article['content']), 75, "\n", true) ?>
            </article>
            <br>
            <small class="article-small">
                Rédigé par <?= $article['firstName'] ?> <?= $article['lastName'] ?> le <?= $article['creationTimestamp'] ?> dans
                la catégorie <?= $article['categoryTitle'] ?></small>
            </section>
            <hr>
            <!-- Sépérateur -->
            <div class="separateur">Commentaires</div>
            <ul class="list-bullpoint-blog">
                <?php foreach($comments as $comment): ?>
                    <li>
                        <h4 class="comment-pseudo"><i class="fa fa-comment"></i>
                            <?= $comment['username'] ?>
                        </h4>
                        <article>
                            <?= nl2br(htmlspecialchars($comment['message'])) ?>
                        </article>
                        <br>
                        <small>Publié le <?= $comment['creationTimestamp'] ?></small>
                    </li>
                    <hr>
                <?php endforeach ?>
            </ul>
            <!-- Formulaire de saisie d'un nouveau commentaire pour cet article -->
            <form class="generic-form" action="add_comment.php" method="POST">
                <input type="hidden" name="id" value="<?= $article['id'] ?>">
                <fieldset>
                    <legend class="comment-form-legend"><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
                        <!-- Pseudo -->
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <label class="comment-form-label" for="username">Votre pseudo</label>
                                        <input type="text" name="username" id="username" class="form-control" rows="1">
                                    </div>
                                </div>
                            </div>
                            <!-- Message -->
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <label class="comment-form-label" for="message">Votre message</label>
                                        <textarea type="text" name="message" id="message" class="form-control" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                            <!-- Boutons -->
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Publier le commentaire</button>
                            </div>
                </fieldset>
            </form>
    </div>
</div>